name: AdvancedChorusFruit
version: 1.1.0
main: me.jiovannyalejos.advancedchorusfruit.AdvancedChorusFruit
api-version: 1.17
authors: [ JiovannyAlejos ]
description: A plugin letting you set specific locations for chorus fruits to take you
commands:
  listwarps:
    description: Sends a list of warp points' names and coordinates to the sender
  removewarp:
    description: Removes a specified warp point
  permission:
    description:
      Modifies players ability to use certain parts of the plugin
      All - All permissions except NoWarping
      Set_Warps - Allow setting warp points
      Remove_Warps - Allow removing of existing warp points
      No_Warping - Disallow using warp points